
seed: 42

datasets:  
  qa-advise-source:
    data_path: "./data/no_segment/qa-advise-source-pos-only.json"
    train_path: "./data/train_test_split/qa-advise-source-pos-only-train.json"
    test_path: "./data/train_test_split/qa-advise-source-pos-only-test.json"
    data_module: "PosOnlyPairDataset"
    test_size: 0.3
    reverse_input: true
    force_remake: false

hf_cache: "./hf_cache"
max_length: 258

# tokenizer: pyvi
pretrained_path: 'minhquy1624/NLI_xnli2_STS'
problem_type: 'BinaryClassification'

criterion: 'MultipleNegativesSymmetricRankingLoss'

max_epochs: 30
batch_size: 128

shuffle_train: true
shuffle_test: false
num_workers: 1
device: "cuda"
optimizer: "AdamW"
lr: 0.0005
model_checkpoints: "./model_checkpoints/biencoder-pair-finetuned/"
train_from_last_epoch: true
