
seed: 42

datasets:
  ViNLI-Zalo-supervised:
    data_path: "./data/no_segment/ViNLI-Zalo-supervised.json"
    train_path: "./data/train_test_split/ViNLI-Zalo-supervised-no-segment-train.json"
    test_path: "./data/train_test_split/ViNLI-Zalo-supervised-no-segment-test.json"
    data_module: "ViNLIZaloRegressionDataset"
    test_size: 0.15
    reverse_input: false
    force_remake: false
    
  # ViNLI-SimCSE-supervised:
  #   data_path: "./data/no_segment/ViNLI-Zalo-supervised.json"
  #   train_path: "./data/train_test_split/ViNLI-SimCSE-supervised-no-segment-train.json"
  #   test_path: "./data/train_test_split/ViNLI-SimCSE-supervised-no-segment-test.json"
  #   data_module: "ViNLIZaloDataset"
  #   test_size: 0.15
  #   reverse_input: true
  #   force_remake: false

  # IR:
  #   data_path: "./data/no_segment/train-IR.json"
  #   train_path: "./data/train_test_split/train-IR-no-segment-train.json"
  #   test_path: "./data/train_test_split/train-IR-no-segment-test.json"
  #   data_module: "IRSegmentDataset"
  #   test_size: 0.15
  #   reverse_input: false
  #   force_remake: false

  # ViMMRC:
  #   data_path: "./data/no_segment/ViMMRC.json"
  #   train_path: "./data/train_test_split/ViMMRC-no-segment-train.json"
  #   test_path: "./data/train_test_split/ViMMRC-no-segment-test.json"
  #   data_module: "ViMMRCSegmentDataset"
  #   test_size: 0.15
  #   reverse_input: false
  #   force_remake: false

  # UIT-ViQuAD:
  #   data_path: "./data/no_segment/UIT-ViQuAD.json"
  #   train_path: "./data/train_test_split/UIT-ViQuAD-no-segment-train.json"
  #   test_path: "./data/train_test_split/UIT-ViQuAD-no-segment-test.json"
  #   data_module: "ViMMRCSegmentDataset"
  #   test_size: 0.15
  #   reverse_input: false
  #   force_remake: false

  # SQuAD-Vi:
  #   data_path: "./data/no_segment/SQuAD-Vi.json"
  #   train_path: "./data/train_test_split/SQuAD-Vi-no-segment-train.json"
  #   test_path: "./data/train_test_split/SQuAD-Vi-no-segment-test.json"
  #   data_module: "ViMMRCSegmentDataset"
  #   test_size: 0.15
  #   reverse_input: false
  #   force_remake: false

tokenizer: "dangvantuan/CrossEncoder-camembert-large"
hf_cache: "../hf_cache"
max_length: 514

pretrained_path: "./model_checkpoints/camembert-large/dvt-camembert-large.pt"
load_state_dict_option: 'force_load'
model:
  model_type: "Camembert"
  hidden_size: 1024
  num_hidden_layers: 24
  num_attention_heads: 16
  intermediate_size: 4096
  hidden_act: "gelu"
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 514
  position_embedding_type: "absolute"
  torch_dtype: "float32"
  type_vocab_size: 1
  layer_norm_eps: 0.00001
  initializer_range: 0.02
  pooler_fc_size: 1024
  pooler_num_attention_heads: 16
  pooler_num_fc_layers: 6
  pooler_size_per_head: 256
  pooler_type: "first_token_transform"
  classifier_dropout: null
  tokenizer_class: 'CamembertTokenizerFast'
  num_labels: 1
  id2label:
    0: LABEL_0
  use_cache: true
  problem_type: null

do_train: true
max_epochs: 20
batch_size: 8

input_fields:
- input_ids
- attention_mask
# - token_type_ids
- position_ids
- labels

shuffle_train: true
shuffle_test: false
num_workers: 1
device: 0
optimizer: "AdamW"
lr: 0.00005
model_checkpoints: "./model_checkpoints/camembert-large-finetune/"
train_from_last_epoch: true

