
seed: 42

datasets:
  ViNLI-Zalo-supervised:
    data_path: "./data/segment/ViNLI-Zalo-supervised.json"
    train_path: "./data/segment/ViNLI-Zalo-supervised-train.json"
    test_path: "./data/segment/ViNLI-Zalo-supervised-test.json"
    data_module: "ViNLIZaloDataset"
    test_size: 0.3

  ViSTS:
    data_path: "./data/segment/ViSTS-segment.json"
    train_path: "./data/segment/ViSTS-segment-train.json"
    test_path: "./data/segment/ViSTS-segment-test.json"
    data_module: "ViSTSDataset"
    test_size: 0.3

tokenizer: "vinai/phobert-base-v2"
hf_cache: "../hf_cache"
max_length: 515

pretrained_path: null
load_state_dict_option: 'encoder_only'
model:
  model_type: "Roberta"
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  hidden_act: "gelu"
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 515
  position_embedding_type: "absolute"
  type_vocab_size: 2
  layer_norm_eps: 0.000001
  initializer_range: 0.02
  classifier_dropout: 0.1
  num_labels: 2
  problem_type: 'single_label_classification'

max_epochs: 300
batch_size: 4
shuffle_train: true
shuffle_test: false
device: 0
optimizer: "AdamW"
lr: 0.0005
model_checkpoints: "./model_checkpoints/classifier/"
train_from_last_epoch: true

