
hf_token: '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'
cache_dir: "/workspace/nlplab/kienvt/KLTN/proc1-extract_storage/hf_cache/"
device: "cpu"

weights: 
  bm25: 1.0
  knn: 1.0
  rerank: 1.0

ranking_strategy:
  name: 'TopK'
  params:
    topk: 20
    relative: true

elastic_search:
  host: "http://192.168.32.1:9200"
  token: 'Ylh4SkRJOEJTcEJhOGhwYlY4TFo6R0p3NUJ6SHFUVTZJd01FSm56RTRtdw=='
  index: "vnr-overlapse00-bkai-biencoder"
  query_strategy: "ensemble"
  query_type: "should"
  activate_fn: "sigmoid"
  scale: 1
  offset: 0.5
  knn_topk: 20
  knn_num_candidates: 100

encoder:
  encoder_name_or_path: 'bkai-foundation-models/vietnamese-bi-encoder'
  segment_api: 
    host: 'http://192.168.32.1:9091/segment2'
    input_field: text
    output_field: sent

rerank_model:
  model_name_or_path: 'dangvantuan/CrossEncoder-camembert-large'
  max_length: 512
  batch_size: 8
  num_workers: 0
  apply_rerank_softmax: true

expand_pool: 
  num_steps: 2
  same_header: false
  expand_first: false